services:
  postgres:
    image: postgres
    container_name: scanwize_test_db
    environment:
      POSTGRES_USER: ${POSTGRES_TESTUSER}
      POSTGRES_PASSWORD: ${POSTGRES_TESTPASSWORD}
      POSTGRES_DB: POSTGRES_TESTDATABASE
    volumes:
      - test-db:/var/lib/postgresql/data
    networks:
      - scanwize_test_app_network
    ports:
      - "${POSTGRES_PORT}:5432"
  scanwize-test-backend:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "${APP_TESTPORT}:3000"
    depends_on:
      - postgres
    volumes:
      - ./:/app
    networks:
      - scanwize_test_app_network
    environment:
      NODE_ENV: test
      APP_PORT: ${APP_PORT}
      POSTGRES_USER: ${POSTGRES_TESTUSER}
      POSTGRES_PASSWORD: ${POSTGRES_TESTPASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_TESTDATABASE}
      POSTGRES_PORT: 5432
volumes:
  test-db:
    driver: local
networks:
  scanwize_test_app_network: