services:
  postgres:
    image: postgres
    container_name: scanwize-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - scanwize_app_network
    ports:
      - "${POSTGRES_PORT}:5432"
  scanwize-backend:
    build:
      context: .
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - postgres
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules/
    environment:
      APP_PORT: ${APP_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PORT: 5432
      NODE_ENV: development

    networks:
      - scanwize_app_network
volumes:
  db:
    driver: local
networks:
  scanwize_app_network: