services:
  postgres:
    image: postgres
    container_name: scanwize_test_db
    environment:
      POSTGRES_USER: scanwize_test_user
      POSTGRES_PASSWORD: scanwize&&strong
      POSTGRES_DB: scanwize_test_db
    volumes:
      - test-db:/var/lib/postgresql/data
    networks:
      - scanwize_test_app_network
    ports:
      - "5434:${POSTGRES_PORT}"
  scanwize-test-backend:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "3005:3000"
    depends_on:
      - postgres
    volumes:
      - ./:/app
    networks:
      - scanwize_test_app_network
    environment:
      NODE_ENV: test
volumes:
  test-db:
    driver: local
networks:
  scanwize_test_app_network: